config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :dogs
  post "/dog", to: "dogs#dog", as: :request_dog
  get "/dog_list", to: "dogs#dog_list"
  get 'store_and_show_dog', to: 'dogs#store_and_show_dog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
require 'net/http'

class DogsController < ApplicationController
  def show
    @dog = Dog.find(params[:id])
  end

  def dog_list
    @dog_data = session[:dog_data]
  end

  def dog
    dog_breed = params[:dog_breed]
    dog_service = DogsService.new(ENV['DOGS_API_KEY'])
    dog_data = dog_service.fetch_dog_by_breed(dog_breed)

    if dog_data.nil?
      handle_api_error("API request failed with status code: #{response.code}")
      return
    end

    if dog_data.length > 1
      store_dog_data_in_session(dog_data)
      return redirect_to('/dog_list')
    end

    handle_dog_data(dog_data[0])
  end

  def store_and_show_dog
    dog_data_json = params[:dog_data].to_json
    dog_data = JSON.parse(dog_data_json)

    handle_dog_data(dog_data)
  end

  private

  def store_dog_data_in_session(data)
    session[:dog_data] = data
  end

  def handle_dog_data(dog_info)
    existing_dog = Dog.find_by(name: dog_info['name'])

    if existing_dog
      redirect_to dog_path(existing_dog)
    else
      create_and_redirect_dog(dog_info)
    end
  end

  def create_and_redirect_dog(dog_info)
    dog_service = DogsService.new(ENV['DOGS_API_KEY'])
    new_dog = dog_service.create_dog(dog_info)

    if new_dog.valid?
      redirect_to dog_path(new_dog)
    else
      handle_dog_creation_error(new_dog)
    end
  end

  def handle_dog_creation_error(new_dog)
    errors = new_dog.errors.full_messages
    render json: { error: "Error creating the new dog: #{errors.join(', ')}" }, status: :unprocessable_entity
  end

  def handle_api_error(message)
    render json: { error: message }, status: :unprocessable_entity
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dogs/dog_list.html.erb
<section id="dog_list_page">
  <div class="dog_list_box">
    <% @dog_data.each do |dog| %>
      <div class="dog_box">
        <h1><%= dog["name"] %></h1>
        <img src="<%= dog["image_link"]%>" alt="">
        <%= link_to "Learn More", store_and_show_dog_path(dog_data: dog), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</section>

app/views/dogs/show.html.erb
<section id="dog_page" data-image-link="<%= @dog.image_link %>">
  <div class="dog_data">

    <div class="left_block">
      <h1><%= @dog.name %></h1>

      <div class="rating_block">
        <div class="rating">
          <p>Good With Children: </p>
          <div class="star-rating" data-rating="<%= @dog.good_with_children %>"></div>
        </div>
        <div class="rating">
          <p>Good With Other Dogs: </p>
          <div class="star-rating" data-rating="<%= @dog.good_with_other_dogs %>"></div>
        </div>
      </div>

      <div class="rating_block">
        <div class="rating">
          <p>Shedding: </p>
          <div class="star-rating" data-rating="<%= @dog.shedding %>"></div>
        </div>
        <div class="rating">
          <p>Grooming: </p>
          <div class="star-rating" data-rating="<%= @dog.grooming %>"></div>
        </div>
      </div>

      <div class="rating_block">
        <div class="rating">
          <p>Drooling: </p>
          <div class="star-rating" data-rating="<%= @dog.drooling %>"></div>
        </div>
        <div class="rating">
          <p>Coat Length: </p>
          <div class="star-rating" data-rating="<%= @dog.coat_length %>"></div>
        </div>
      </div>

      <div class="rating_block">
        <div class="rating">
          <p>Good With Strangers: </p>
          <div class="star-rating" data-rating="<%= @dog.good_with_strangers %>"></div>
        </div>
        <div class="rating">
          <p>Playfulness: </p>
          <div class="star-rating" data-rating="<%= @dog.playfulness %>"></div>
        </div>
      </div>

      <div class="rating_block">
        <div class="rating">
          <p>Protectiveness: </p>
          <div class="star-rating" data-rating="<%= @dog.protectiveness %>"></div>
        </div>
        <div class="rating">
          <p>Trainability: </p>
          <div class="star-rating" data-rating="<%= @dog.trainability %>"></div>
        </div>
      </div>

      <div class="rating_block">
        <div class="rating">
          <p>Energy: </p>
          <div class="star-rating" data-rating="<%= @dog.energy %>"></div>
        </div>
        <div class="rating">
          <p>Barking: </p>
          <div class="star-rating" data-rating="<%= @dog.barking %>"></div>
        </div>
      </div>
    </div>

    <div class="right_block">
      <img src="<%= @dog.image_link%>" alt="">

        <div class="data_block">
          <div class="data">
            <p>Life Expectancy: <%= @dog.min_life_expectancy.to_i %> - <%= @dog.max_life_expectancy.to_i %> years</p>
          </div>
        </div>

        <div class="data_block">
          <div class="data">
            <p>Height Male: <%= @dog.min_height_male.to_i %>&Prime; - <%= @dog.max_height_male.to_i %>&Prime; </p>
          </div>
          <div class="data">
            <p>Height Female: <%= @dog.min_height_female.to_i %>&Prime; - <%= @dog.max_height_female.to_i %>&Prime; </p>
          </div>
        </div>

        <div class="data_block">
          <div class="data">
            <p>Weight Male: <%= @dog.min_weight_male.to_i %>lb - <%= @dog.max_weight_male.to_i %>lb </p>
          </div>
          <div class="data">
            <p>Weight Female: <%= @dog.min_weight_female.to_i %>lb - <%= @dog.max_weight_female.to_i %>lb</p>
          </div>
        </div>

    </div>
  </div>
</section>

<%= javascript_include_tag "dog_page" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WoofWise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/dog_search_form' %>
    <%= render partial: 'shared/home_btn' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<section id="landing-page">
  <div class="landing-text">
    <h1>WoofWise</h1>
    <p>Welcome to the ultimate destination for all your canine curiosity! Our dog information search website is your go-to resource for everything related to man's best friend. Whether you're a seasoned dog owner looking to deepen your understanding of your furry companion or a prospective dog parent seeking guidance, you've come to the right place. Our extensive database is brimming with expertly curated articles, comprehensive breed profiles, training tips, health advice, and much more. Unleash your passion for dogs and embark on a journey of knowledge and companionship with us. Let's explore the fascinating world of dogs together!</p>
  </div>
</section>

app/views/shared/_dog_search_form.html.erb
<div id="search_form_btn">
  <i id="search_form_icon" class="fa-solid fa-magnifying-glass"></i>
</div>

<div id="search_form" class="hide_form">
  <%= form_tag(request_dog_path, method: "post", id: "dog_form") do %>
    <div class="search_form_header">
      <label for="dog_breed">Search a Breed</label>
      <i id="close_form_btn" class="fa-solid fa-xmark"></i>
    </div>
    <%= text_field_tag :dog_breed, nil, id: "dog_breed" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<%= javascript_include_tag "search_form" %>

app/views/shared/_home_btn.html.erb
<a id="home_btn" href="/">
  <i class="fa-solid fa-house"></i>
</a>